# Generated by Django 4.2.3 on 2023-07-22 08:47

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("services", "0001_initial"),
    ]

    operations = [
        migrations.RenameModel(old_name="Rewiew", new_name="Review",),
    ]
