# Generated by Django 4.2.3 on 2023-07-22 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("services", "0002_rename_rewiew_review"),
    ]

    operations = [
        migrations.AddField(
            model_name="service",
            name="image_url",
            field=models.CharField(max_length=200, null=True),
        ),
    ]
